FROM ubuntu:22.04

RUN apt-get update \
 && apt-get install -y build-essential scons libevent-dev gengetopt memcached \
 && rm -rf /var/lib/apt/lists/*

COPY ../third-party/mutilate /mutilate

WORKDIR /mutilate

RUN scons

CMD memcached -d -m 64 -p 11211 -u nobody && ./mutilate -s localhost

# docker build -t mutilate-image -f Dockerfile.mutilate .
# docker run -it --name mutilate-container mutilate-image /bin/bash
