FROM ubuntu:22.04

RUN apt-get update \
 && apt-get install -y openssl libapr1 libnuma1 libsubunit0 \
    iproute2 libnl-3-dev libnl-route-3-dev python3 iputils-ping  \
    vim gdb libunwind-dev memcached \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["memcached", "-u", "memcache"]

# docker build -t memcached-test -f Dockerfile.test .
# docker run -d --name memcached-container -p 11211:11211 memcached-test
# telnet localhost 11211
