ARG UBUNTU_VERSION

FROM ubuntu:${UBUNTU_VERSION}

RUN apt-get update \
 && apt-get install -y nginx \
 && rm -rf /var/lib/apt/lists/*

COPY resources/nginx/nginx_server_mirroring.conf /nginx.conf
COPY script/nginx_mirroring_entrypoint.sh /usr/bin/nginx_mirroring_entrypoint.sh
COPY third-party/mutilate/mutilate /usr/bin/

ENTRYPOINT ["nginx", "-c", "/nginx.conf"]
